// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Локальная разработка: postgresql://onboard:onboard_secret@localhost:5432/onboard (см. docker-compose)
    url: process.env["DATABASE_URL"],
  },
});
